Map 2 small doctor card
TheYellowHub/TheMap pull request #8
Opened 2023-10-04 23:40 UTC by xiushak

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorSmallCard.tsx
> +import { Tooltip, OverlayTrigger } from "react-bootstrap";
Import orders:
In all the files, import from react etc should be before all the imports from our components

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorSmallCard.tsx
> +    const image = doctor.image
The doctor image, including this calc, should be in a separated component

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorSmallCard.tsx
> +                            {doctor.category || "No Category"}
No need to write "No Category"

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorSmallCard.tsx
> +                        <span className="verification">
Should be another component

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorSmallCard.tsx
> +                    <div className="bookmarkRibbon col-auto">
The name "bookmarkRibbon" is confusing since we do have a bookmark symbol in the big card... 
Maybe "doctorCategoryRibbon"?

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorSmallCard.tsx
> +                                        onClick={(e) => e.stopPropagation()}
I'm using chrome and e.stopPropagation() didn't solve the issue here. The card was opened first, and for some reason. this one got opened in the same tab :/

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorSmallCard.tsx
> +                        {closestLocation &&
Should be another component + It doesn't work

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorSmallCard.tsx
> +                                        <i className="fas fa-location-arrow p-0"></i>
Please use "Icon" component

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorSmallCard.tsx
> +                <div className="text-black row w-100 m-0 mt-auto">
Should be another component

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/StarRating.tsx
> +function StarRating({ rating }: { rating: number }) {
Please define the props separately, like in the other files

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/StarRating.tsx
> +                stars.push(<i className="fas fa-star p-0"></i>);
Please use "Icon" component

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/index.css
> +}
Please add empty lines

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/index.css
> +    width: 26rem; /* TODO: change? */
Is the TODO relevamt?

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorSmallCard.tsx
> +import {
Please do some minimal responsiveness tests. Using chrome devtools or even without, after I changed the window size, I got some "pretty" results, such as:
![image](https://github.com/TheYellowHub/TheMap/assets/42554587/48017419-d291-4aed-9168-7fd939e76971)

2023-10-10 11:26 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorSmallCard.tsx
> +                            {closestLocation?.address || ""}
Not sure we shouldn't show all the locations - Let's ask Ruthy about it

2023-10-18 13:36 UTC, HanaBenami requested changes

2023-10-18 13:36 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorDistance.tsx
> +    location: DoctorLocation | null | undefined;
Please call It doctor location.
Location is too general and we have another location here.

2023-10-18 13:36 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorDistance.tsx
> +                        location.address || ""
If location.address is undefined, we shouldn't get to this code... A link with "" doesn't make sense.

2023-10-18 13:36 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorSmallCard.tsx
> +                    </div>
Do we need a ribbon if there is no category?
In addition, I think it should be another separated component

2023-10-18 13:36 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorDistance.tsx
> +function DoctorDistance({
The component should be Doctor location address and should also include the address itself

2023-10-18 13:36 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/StarRating.tsx
> +                    <Icon icon="fa-star" solid={true} padding={false} />
Please use a variable for the icon name in the if/else if/else, and then write only once: stars.push(<Icon ...>)

2023-10-18 13:36 UTC, HanaBenami commented on frontend/src/index.css
> +    line-height: 1.25rem; /* 125% */
You can delete the comment 125%

2023-10-18 18:03 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/DoctorDistance.tsx
> +        <Tooltip>No link to address</Tooltip>
Why do we need it?

2023-10-18 18:03 UTC, HanaBenami commented on frontend/src/components/doctors/doctors/StarRating.tsx
>      }
Much better and shorter!

2023-10-24 04:29 UTC, HanaBenami approved these changes

2023-10-24 04:29 UTC, TheYellowHub approved these changes

2023-10-24 04:30 UTC, merged